### ISSUE TITLE
Saymon21,  по теме хабов

### ISSUE THREAD

**Issue by dcbeelinekz** [dkhabarov/RusHub-Lua-Scripts#2]
Хотел бы у тебя попросить помощи насчет скрипта или добавления этой функции в  исходник сервера птохи 0.5.0.1. Если не затруднит тебя этот вопрос
Если юзер повторно подключается с одним ником и IP тоже одинаковый, то предыдущая копия удаляется из хаба

Относительно по этой теме http://mydc.ru/index.html?showtopic=4665&view=findpost&p=37275

> А на сервере..Тут, наверное, если получится придумать скрипт, который при проверке ника нового юзера будет вместо быстрого ValidateDenide при наличии такого же ника делать сначала некую проверку-пинг (запрос IP, что-ли) соединения..

**Comment by dkhabarov** [comment]
Я сейчас не занимаюсь хабами.

**Comment by dcbeelinekz** [comment]
лан, знай что ты был красивый на хабах, твои текста еще находятся гуглом и помогают 
Дай Бог тебе здоровья
